#Here is an exemple of how to create a generator
#Please notice that you HAVE to name the file with the AREA value. The file here would be named Blacksmith.yml
#This means that you must have one config file per generator
#
#area: Blacksmith
#Blacksmith-values:
# material: STONE
# x: '0'
# y: '100'
# z: '0'
# world: world
# amount: '1'
# time: '72000'
# isEnabled : '1'
# 72000 is the default value, 72000 ticks equals to 1 hour