name: Quartiers
desc: Allows you to create a ressource generator in your server
main: fr.emetros.quartiers.main
version: 1.0
api-version: 1.16
commands:
  quartierscreate:
    basic: quartierscreate
    description: /createquartier area_name  type coords_of_the_chest
    permission: quartiers.create
    permission-message: You are not allowed to create a ressource generator !
  quartiersdisable:
    basic: quartiersdisable
    description: /disablequartier area_name
    permission: quartiers.disable
    permission-message: You are not allowed to disable a ressource generator !
  quartiersreload:
    basic: quartiersreload
    description: Allow you to reload ressource generators
    permission: quartiers.reload
    permission-message: You are not allowed to reload Quartiers !
  quartiersenable:
    basic: quartiersenable
    description: Allow you to load a specific ressource generator
    permission: quartiers.enable
    permission-message: You are not allowed to load a generator !
  quartierslist:
    basic: quartierslist
    description: Lists the generators that you've created
    permission: quartiers.list
    permission-message: You are not allowed to list generators !
permissions:
  quartiers.*:
    description: Allows you to use all quartiers's commands
    children:
      quartiers.create: true
      quartiers.disable: true
      quartiers.reload: true
      quartiers.enable: true
      quartiers.list: true
  quartiers.create:
    description: Allows you to create a ressource generator
    default: op
  quartiers.disable:
    description: Allows you to disable a ressource generator
    default: op
  quartiers.reload:
    description: Allows you to reload Quartiers
    default: op
  quartiers.enable:
    description: Allows you to enable a ressource generator
    default: op
  quartiers.list:
    description: Allows you to get the list of all the generators
    default: op